spring:
  datasource:
    url: jdbc:h2:file:~/testedb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8082
