spring:
  datasource:
    url: jdbc:h2:mem:testedb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.H2Dialect
server:
  port: 8082
